App\Api\Contact\Domain\Entity\ContactForm:
  shortname: 'Contact'
  description: 'Contact Endpoints'
  itemOperations: []
  collectionOperations:
    contact_form:
      method: 'POST'
      description: 'Receive a message from user'
      path: '/contact'
      controller: 'App\Api\Contact\Infrastructure\Controller\UserSendMessageController'
      deserialize: false
      openapi_context:
        summary: 'Receive message from user'
        description: 'Receive message from contact form.'
        requestBody:
          description: 'Sent message to platform'
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  email:
                    type: 'string'
                  message:
                    type: 'string'
        responses:
          '200':
            description: 'Message sent'
            content:
              application/json:
                schema:
                  type: 'object'
                  properties:
                    status:
                      type: 'string'
                    message:
                      type: 'string'